### ISSUE TITLE
Confusing output in Patch_yearly files

### ISSUE THREAD

**Issue by RuilingLu** [wengensheng/BiomeESS#3]
Hi Weng laoshi@wengensheng, I'm running the latest version of BiomeESS using the default forcing data of ORNL. It's a 100-year-long simulation with the U_shaped mortality module, but model triggers a note to in kill_lowdensity_cohorts: All cohorts < mindensity after 14 running years. I did following steps to identify the problems: (1) change the forcing data and no complain about the low density cohorts, (2) test the running year from 20-500 and failed right away with the same issue.

Could you please look into this issue and help me resolve it?

Thanks!
Ruiling

FYI: the model crashed with note as following:
(https://user-images.githubusercontent.com/59443207/209424393-1b50382d-8b61-487c-84d7-054cc57272b9.png)

**Comment by wengensheng** [comment]
Hi, Ruiling,
Sorry for the bugs. I have fixed it and other input/output issues, and released a new version (v2.01). The plant hydraulics module is not working well at ORNL. You may comment out "#define Hydro_test" (the first line in vegetation.f90). I prefer to download the new release since I also fixed the issues in the sapwood calculation for the non-hydraulics version.

Ensheng

**Comment by RuilingLu** [comment]
It works now. Thanks so much for your help!

**Comment by wengensheng** [comment]
A new version has been released for solving this issue with a new setting of input and output
